### ISSUE TITLE
Can't open google key and certificate file

### ISSUE THREAD

**Issue by cgyan009** [simllll/node-radius-server#342]
Hi Guys,

Configured according to the md files. but got this errors:

app] Listener Port: 1812
[app] RADIUS Secret: CLEA$999
[app] Auth GoogleLDAPAuth
[app] cannot load auth mechanisms GoogleLDAPAuth
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'Google_2025_10_10_50052.key'
    at Object.openSync (node:fs:585:3)
    at Module.readFileSync (node:fs:453:35)
    at new GoogleLDAPAuth (file:///Users/frankyan/Desktop/node-radius-server/dist/auth/GoogleLDAPAuth.js:10:21)
    at file:///Users/frankyan/Desktop/node-radius-server/dist/app.js:50:16 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'Google_2025_10_10_50052.key'

I put the files in ssl/cert. 

Any hints? 

Many thanks,

**Comment by avicoder** [comment]
put the keys in root folder.
Make sure to name the keys as mentioned in README.md
<img width="138" alt="image" src="https://user-images.githubusercontent.com/2093260/216779784-03dd3268-dd42-41a3-875c-40098e6b7757.png">
