### ISSUE TITLE
certificate routines:X509_check_private_key:key values mismatch

### ISSUE THREAD

**Issue by ruslan-gennadievich** [simllll/node-radius-server#97]
Hello

After run ./ssl/create.sh i have error 

`_tls_common.js:145
        c.context.setKey(pem, val.passphrase || passphrase);
                  ^

Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:145:19)
    at Object.<anonymous> (/home/ruslan/Документы/node-radius-server/dist/tls/crypt.js:19:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ruslan/Документы/node-radius-server/dist/radius/handler/eap/eapMethods/EAP-TTLS.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  library: 'x509 certificate routines',
  function: 'X509_check_private_key',
  reason: 'key values mismatch',
  code: 'ERR_OSSL_X509_KEY_VALUES_MISMATCH'
}`

**Comment by afgarcia86** [comment]
I am also having this issue

**Comment by simllll** [comment]
Verify the passcode you used for generating the asl certificates is the same as in the config of the node radius server!

**Comment by afgarcia86** [comment]
For me it was related to not opening in UTF-8. I just got it working!

`certificate: {
	cert: fs.readFileSync(path.join(SSL_CERT_DIRECTORY, '/server.crt'), 'utf8'),
	key: [
		{
			pem: fs.readFileSync(path.join(SSL_CERT_DIRECTORY, '/server.key'), 'utf8'),
			passphrase: 'whatever2020',
		},
	],`

**Comment by virus2016** [comment]
Hi @simllll,

I have just cloned your project and I can't get it started. I've tried the above, used your certs and get 

```
Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:145:19)
    at Object.<anonymous> (/workspaces/node-radius-server/src/tls/crypt.ts:18:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/workspaces/node-radius-server/node_modules/ts-node/src/index.ts:1295:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/workspaces/node-radius-server/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
```

Im not sure what I am doing wrong... I've tried to generate my own certs and had to update your scripts

```
	"scripts": {
...
		"create-certificate": "cd ./ssl && sh ./create.sh && cd .."
	},
```

**Comment by virus2016** [comment]
Got it working, forgot to remove the top section of the server.crt ;-)
